settings:
  link: "http://www.railstutorial.org/"
  help: "http://www.railstutorial.org/help"
  book: "http://www.railstutorial.org/book"
  news: "https://news.railstutorial.org/"
  contact: "https://news.railstutorial.org/contact"
  about: "https://news.railstutorial.org/about"
  author: "https://www.michaelhartl.com/"
  name_maximun_length: 50
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  email_maximun_length: 255
  password_minimun: 6
  gravatar_email: "http://gravatar.com/emails"
  gravatar_url: "https://secure.gravatar.com/avatar/#"
  avatar_size: 50
  paging_numbers: 10
  expired_password_time: 2
  content_maximum_length: 140
  item_per_page: 10
  micropost_size: 50
  image_type: ["image/jpeg", "image/gif", "image/png"]
  image_types: "image/jpeg, image/gif, image/png"
  max_image_size: 5
  image_limit: 500

  # localhost
  localhost: "localhost:3000"
